spring:
  application:
    name: kaizen-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/<YOUR_DB_NAME>
    # url: jdbc:postgresql://localhost:5432/kaizen-bokaro-database
    username: <DB_USERNAME>
    password: <YOUR_PASSWORD>
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

# üîê JWT Configuration (THIS WAS MISSING)
jwt:
  secret: kaizen-secret-key-kaizen-secret-key-kaizen-secret-key
  expiration: 3600000
